### PR TITLE
Created the about.js file displaying the info of the bot

### PR DESCRIPTION
**Pull request by sidtr0**
Right now, it would work something like this. 

```
@Chronos about
```
or 
```
+about
```

So we still have to make it display the about result only by pinging. So I will work on that sometime soon. Pull requested anyway.

### CODE REVIEW

**Comment by ItsAzaria** [comment]
I think as discussed on discord, making the embed a bit cleaner like 
image would be preferred. 
Along with responding on just a mention, you may have to use an event to do this 
https://discord.js.org/#/docs/main/stable/class/Client?scrollTo=e-message

**Comment by sidtr0** [comment]
If what you want is a the profile picture thumbnail in the the embed, I can do it.

**Comment by ItsAzaria** [comment]
There's a few very minor things that would improve the looks of this greatly

Inline fields for prefix, contributors, uptime and ping
can be done with 
```{name: "**Prefix**", value: `${this.handler.prefix}`, inline: true},```

Adding the profile picture thumbnail is perfect too, I've just noticed but it seems you've deleted the .env.example file too. Perhaps by mistake

**Comment by sidtr0** [comment]
Okay I'll work on that.

Also, I apologize about the `.env.example`. I think we can close this PR and I'll open a new updated one. That okay?

**Comment by ItsAzaria** [comment]
That works for me, one extra thing I think would help out with looks is to style the build info text, should be able to do it with something like

`{name: "**Build info**", value: "```fix\nVersion: 0.0.0\nDiscord.js: v12.3.1\nDiscord Akairo: v8.2.0```"},`

No worries about the .env.example - easy enough mistake to make

**Comment by sidtr0** [comment]
image
It looks like this. Thanks for the suggestions, it looks much cleaner now. 

I am still working on getting it to work by just mentioning it. I'll open a new PR when I fix that.

**Comment by sidtr0** [comment]
Missed a few other things mentioned on the Discord channel, so here they are updated as well.

image

**Comment by ItsAzaria** [comment]
Looking great!

**Comment by sidtr0** [comment]
Closing PR because I'm creating a new updated one.

**Pull request closed without merging**
